# Generated by Django 4.0 on 2022-10-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, editable=False, help_text='student image', upload_to='QR')),
                ('first_name', models.CharField(help_text='student first name', max_length=19)),
                ('last_name', models.CharField(help_text='student last name', max_length=19)),
                ('email', models.EmailField(help_text='student email', max_length=254)),
                ('reg_no', models.CharField(help_text='registration number ', max_length=16)),
                ('gadget_brand', models.CharField(help_text='e.g. hp', max_length=15)),
                ('gadget_model', models.CharField(help_text='folio 9470', max_length=15)),
                ('gadget_serial', models.CharField(help_text='CNU4149***', max_length=15)),
                ('gadget_os', models.CharField(choices=[('windows', 'Windows'), ('harmony', 'harmony'), ('ubuntu', 'ubuntu'), ('ios', 'ios'), ('android', 'android'), ('linux', 'linux')], max_length=8)),
                ('reg_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
