# Generated by Django 4.1.1 on 2022-10-04 06:08

from django.db import migrations, models
import generator.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_no', models.CharField(max_length=14)),
                ('email', models.EmailField(max_length=254)),
                ('qr_code', models.ImageField(upload_to=generator.models.folder)),
            ],
        ),
    ]
